#!/bin/sh

if [ -z "$MENU" ]
then
	MENU="dmenu"
fi

case $(echo "$MENU" | tr '[:upper:]' '[:lower:]') in
*dmenu*)SELECT=$MENU" -c -l 10 ";;
*)SELECT="$MENU";;
esac

file=$(ls -arF1 | $SELECT)

case $(echo "$file" | tr '[:upper:]' '[:lower:]') in
*/)
cd "$file"
. sf
;;
*)sopen "$file";;
esac