#!/bin/sh

if [ -z "$MENU" ]
then
	MENU="dmenu"
fi

case $(echo "$MENU" | tr '[:upper:]' '[:lower:]') in
*dmenu*)SELECT=$MENU" -c -l 10 ";;
*)SELECT="$MENU";;
esac

case $(echo "$1" | tr '[:upper:]' '[:lower:]') in
	-a)file=$(ls -rF1 | $SELECT);;
	*)file=$(ls -arF1 | $SELECT);;
esac

case $(echo "$file" | tr '[:upper:]' '[:lower:]') in
*/)
cd "$file"
. sf
;;
*)sopen "$file";;
esac